travis:
  secure:
    BINSTAR_TOKEN: ArQh0nm0x9ea1PoOLWsbMKCr8lDHgaaVnCfWoMJLHKjEVWWcckCT63COFUzVnRkr4Bzdof0evepUmA8JGSeQJm89GTr3cqG9vMM1/HHQVLcnuP+lvxnZU28YYoWqnZR0gkMIFaiBKDJmQLLwMOAPrR0iUw4geTkezd5RopwDddBBI2wRDqcqyb6aC8CqI86D1zYHAR/ktOc9IpJux2pxdIv0p/FN1cvZX7V82umjNYqmibBHBGg0iFW/dBsoA3QIr81PBLwvQnBFB6KdL9uSPyFEboIHkZFWQKVuajIWjXYh9qBhwXmJwipNGeO3vboeDbKsubSWldBPpRqfXXf3TwYq5QbQTqhRdYaPX2dgut4fJcsr6n7/pQkQI2lVXQQjIE4s/J2iBbKam03ug5vSE4wzqaq7SH3k+xQ1pYFpFOM30LEtpUU1uActPvvsxvxRlj1bbg6aSGG623vloYHzplbj1PBR3r6LAWVjzRsGqBnwRh91i4FalKLKcfD2tSL5Wn1jAD4VDDBFlSLXo151yts1QWVuHf9QQH+VA0+yNnIMPSYO19CA0MhBoSfeE/GhFeJ6MuktXsr8NCs1ZdE7zumICuu1dp6JLNzIkDm/TjCMjnYWXZ5fBEZa5dhc84Khimhfa5EjjqJ9wMpo3Z/TolfTtFOFuEYGO2fgPD/rVlA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
