travis:
  secure:
    BINSTAR_TOKEN: bmh0o4fhMUOCw6q0pCwyOdKMS7y593hd2ZZlwI/xTr3THai/fxWwlqpdEQ7V92ZvtWWwSphqnIkqP+ebQPwStOhwm+IJJ3oBYjhZY5baJVUfMLpxn+/q958bg+gYYTBrCrLnOoMAZIwVckHRFsgxurVMQjMGp9ib3hvZlg3itEk8B+MynAGqxpvPStC8mevtsDCgXMYraZtisWo6Q68D7ZoR7D+emYA0tZHj0lZNVZoEWeyCTdF7vKcGtKtj1HegSYdebfDZqexEQOROeN5jY3KRaWrNc9e50In+Mi1OL08OYZZkx0dMhG7zZqc08mm6ZJYdU29+UpOmI+E8bM4TxnZs/M0LAsLbZU4eHbjAK2mPgyTvMST3QqQWkFwmA1lqu2iHQ7A7OdNX8nq7+M5nJTttTlnFEwKkx3rSc3ProLdaKJHYsoE6C2tPOukhwkkNCuuhY2dC5iJWBHajwE9DXuI6zsOtukzxGFybcYZxuSMmR91RU+pW5lrkkIqGqwEDYdWgSmkSHE7CMNyGAsmK+h9+emNat6dbgWB3X6bsDt2K7kLtCGfqqtUH0IbsrM2O9KvsXml97w/C34zMAwYl8LqXdPFuX2cAw8hxaVzGYi2h2NSR6ROOvS4Tu2m2B3Jhbe96+8N80nX+fwhde6UjqK4Z2tmek1RO64l3LOJEsWE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
